### ISSUE TITLE
Dice pool modifiers

### ISSUE THREAD

**Issue by censlin** [Ohmnibus/quick-dice-roller#7]
Some games (shadowrun) apply modifiers to the pool size.
Currently adding a bonus can be emulated easily enough by adding another dice roll, but removing dice is a different story. My best workaround at the moment is to ignore a random die (selected by rolling a die in meatspace)

**Comment by Ohmnibus** [comment]
A Named Value can be used as the number of dice to roll:
Named Value: `pSize`
Formula: `shrun4(1d6, pSize, 5, 6, 1)`

**Comment by censlin** [comment]
My bad. That works much better
